#!/bin/bash
# Generates the dependencies of a Fortran 90 source file
#
# Dependencies : grep, sed, tr, sort, uniq, basename
#

### functions
function PrintHelpAndExit
{
cat <<EOF
$(basename $0)

NAME
   $(basename $0) - Extract the module dependencies of a Fortran 90 source file.

SYNOPSIS 

   $(basename $0) [OPTION]... FILE

DESCRIPTION

  Extract the modules dependencies from a Fortran 90 source file. 
  The result is print on standard output in GNU/Make format.

  By default, this scripts assumes that the modules files generated 
  are in lower cases, with the suffix ${modext}.

  -h 
     print this help and exit

  -f <suffix>
     Fortran file suffix (default .F90)

  -m <suffix> 
     defines the suffix of modules files (default is '${modext}').

  -p <prefix>
     defines the suffix of prefix files (default is '').
  -u 
     the modules files generated by the compiler are in upper cases.

  -l 
     the modules files generated by the compiler are in lower cases. (Default)

  -w 
     the modules files are weakly linked to the source file.
     Indeed, the rules generated are in order-only (ie <file> : | <module>)
  
AUTHOR

    Yohan Lee-tin-yien <yohan.lee-tin-yien@inria.fr>

EOF

exit 0;

};

### main

filext=.F90
modext=.mod
modcase="LOWER"
modprefix=""
orderonly=""
# not enough arguments
NO_ARGS=0 
[ $# -eq "$NO_ARGS" ] && PrintHelpAndExit;

# option
while getopts "huf:lm:p:w" Option
do
    case $Option in
	h ) PrintHelpAndExit;;
	u ) modcase="UPPER";;
	f ) filext="$OPTARG";;
	l ) modcase="LOWER";;
	m ) modext="$OPTARG";;
	p ) modprefix="$OPTARG";;
	w ) orderonly="|"
    esac
done
shift $(($OPTIND - 1))

## do the job
file=$1
mods=( `grep -E "^ *[Uu][Ss][Ee] *" ${file} | sed 's/[!,].*//g' | sed 's/^ *[Uu][Ss][Ee] *//g' | sort | uniq` );

echo "# This file was generated by $(basename $0) from ${file}"
for mod in ${mods[@]}
do
    [[ "${modcase}" == "LOWER" ]] && modname=$(echo ${mod} | tr '[:upper:]' '[:lower:]')
    [[ "${modcase}" == "UPPER" ]] && modname=$(echo ${mod} | tr '[:lower:]' '[:upper:]')
    objname=${file%${filext}}.o
    echo "${objname} : ${orderonly} ${modprefix}${modname}${modext}" 
done




